# Generated by Django 4.1.3 on 2022-11-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_admin_user_type_employee_user_type_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='aministrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.administrator'),
        ),
    ]
