# Generated by Django 4.1.3 on 2022-11-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_aministrator_authcode_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='location',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.administrator'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
